# Generated by Django 3.0.5 on 2020-05-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivering',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='delivertime',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
